### ISSUE TITLE
Retrieving optional fields

### ISSUE THREAD

**Issue by raboof** [mirage/ezjsonm#13]
Wouldn't it make sense to have a variation on 'find' that returns an option instead of raising an error when no element is found?

**Comment by samoht** [comment]
yes, that would be useful!

**Comment by raboof** [comment]
Should we rename `find` to `find_exn` and change `find` to return an option? Or do we care deeply about backwards compatibility?

**Comment by samoht** [comment]
don't worry too much about backward compatibililty, we will just need to add some version constraints in the opam-repository for the next release.
