### ISSUE TITLE
Jsoo + Ezjsonm: "Too much recursion" in Firefox console when reading/writing Json-list 

### ISSUE THREAD

**Issue by rand00** [mirage/ezjsonm#20]
I found this issue by using Cow in a Jsoo compiled program to read a json-list of data; and now found that the failure also appears when running the following with Firefox:

```
Array.(`A (to_list (make 1000 (`O [("bar", `String "baz")]))))
|> Ezjsonm.to_string 
```

The problem doesn't seem to appear with Chromium. Guess it might as well be an issue with Firefox not handling recursion properly...

**Comment by dinosaure** [comment]
Should be fixed in the current status of `ezjsonm`, can you test it please?

**Comment by rand00** [comment]
Yes, works with my local current version: `1.0.0 [4.07.1]`
