### ISSUE TITLE
Assertion failure when parsing a number

### ISSUE THREAD

**Issue by hcarty** [mirage/ezjsonm#31]
Testing with OCaml 4.04.2 and ezjsonm 0.5.0 from opam:
```ocaml
─utop # Ezjsonm.from_string "1";;
Exception: Assert_failure ("lib/ezjsonm.ml", 58, 59).
```
I know (ez)jsonm requires a wrapping array/object but an assertion failure seems worth reporting.

**Comment by abate** [comment]
Same problem here. Instead of `assert false` this function should raise a parsing error
