### ISSUE TITLE
Missing online documentation.

### ISSUE THREAD

**Issue by sagotch** [mirage/ezjsonm#9]
- I like to have the possibility to read documentation without having to generate it.
- Github pages are perfect for this purpose.
- Ezjsonm does not provide any known online documentation.

So, I started to add a rule to Makefile to generate documention and push it to gh-pages, and ended with a script (https://github.com/sagotch/ghpup), because the Makefile rule was a mess...

You can see it "in action" on my fork, where I used it to generate github pages for Ezjsonm (https://github.com/sagotch/ezjsonm/blob/master/Makefile#L54).

If you want to merge the script into mirage/ezjsonm, it would be with great pleasure. If you do not, gh-pages branch still is a good idea. :)

**Comment by samoht** [comment]
ghpup looks great!!! (I always wanted such a tool)

**Comment by samoht** [comment]
A patch  with a target to build the doc would be great

**Comment by sagotch** [comment]
I actually just removed the script and the rule from my repo, because it implied to add ghpup script to the repo. I thought it was a little bit intrusive.

Would you prefer the script to be added in the repo or just the rule in the Makefile, assuming that `ghpup` in available in the path?

**Comment by samoht** [comment]
The rule is the Makefile is fine, with an associated ghpup package in opam would be great. I have similar stuff in https://github.com/samoht/irmin/blob/master/Makefile#L56 for instance

**Comment by samoht** [comment]
This is now fixed: http://mirage.github.io/ezjsonm/Ezjsonm.html
